/* BSD 3-Clause License
 *
 * Copyright (c) 2017, Louis Jenkins <LouisJenkinsCS@hotmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     - Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *
 *     - Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 *     - Neither the name of Louis Jenkins, Bloomsburg University nor the names of its 
 *       contributors may be used to endorse or promote products derived
 *       from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package llvm.jvm.frontend;

import java.awt.BorderLayout;
import java.awt.Font;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import org.fife.ui.rtextarea.*;
import org.fife.ui.rsyntaxtextarea.*;

/**
 *
 * @author Louis Jenkins
 */
public class Editor extends javax.swing.JFrame {
    
    private static String LLVM_JVM_PATH = "/home/awsgui/LLVM-JVM/";
    
    private RSyntaxTextArea editor;
    private static String defaultContents = "class Addition {\n" +
                        "\n" +
                        "  public static int result;\n" +
                        "\n" +
                        "  public static int RunMe() {\n" +
                        "    int x = 0x1000;\n" +
                        "    int y = 0x2000;\n" +
                        "    int z = 0x3000;\n" +
                        "    int w = x + y + z;\n" +
                        "\n" +
                        "    if (w > x) {\n" +
                        "      result = w;\n" +
                        "    } else if (y > w) {\n" +
                        "      result = y;\n" +
                        "    } else if (z > w) {\n" +
                        "      result = z;\n" +
                        "    } else {\n" +
                        "      result = x;\n" +
                        "    }\n" +
                        "\n" +
                        "    return result;\n" +
                        "  }\n" +
                        "\n" +
                        "  public static void main(String[] args) {\n" +
                        "\n" +
                        "  }\n" +
                        "}";

    /**
     * Creates new form Editor
     */
    public Editor() {
        initComponents();
        
        editor = new RSyntaxTextArea(20, 60);
        editor.setFont(new Font("Arial", Font.PLAIN, 20));
        editor.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
        editor.setCodeFoldingEnabled(true);
        editor.setText(defaultContents);
        RTextScrollPane sp = new RTextScrollPane(editor);
        TextEditorPanel.add(sp);

        setTitle("Text Editor Demo");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        pack();
        setLocationRelativeTo(null);
        
    }
    
    public static String getBaseName(String fileName) {
        int index = fileName.lastIndexOf('.');
        if (index == -1) {
            return fileName;
        } else {
            return fileName.substring(0, index);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        buttonGroup1 = new javax.swing.ButtonGroup();
        TextEditorPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        OutputBytecode = new javax.swing.JTextArea();
        OutputUnoptimizedIR = new javax.swing.JPanel();
        OutputOptimizedIR = new javax.swing.JPanel();
        OutputOptimizedIR2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        TextEditorPanel.setLayout(new java.awt.BorderLayout());

        OutputBytecode.setEditable(false);
        OutputBytecode.setColumns(20);
        OutputBytecode.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        OutputBytecode.setRows(5);
        jScrollPane3.setViewportView(OutputBytecode);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ByteCode", jPanel2);

        OutputUnoptimizedIR.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("LLVM IR (Unoptimized)", OutputUnoptimizedIR);

        OutputOptimizedIR.setLayout(new java.awt.BorderLayout());

        OutputOptimizedIR2.setLayout(new java.awt.BorderLayout());
        OutputOptimizedIR.add(OutputOptimizedIR2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("LLVM IR (Optimized)", OutputOptimizedIR);

        jMenu1.setText("Run");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TextEditorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextEditorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        System.out.println(TextEditorPanel.toString());
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        try {
            String txt = editor.getText();
            File tmpDir = Files.createTempDirectory("tmp").toFile();
            File tmpFile = File.createTempFile("tmp", ".java", tmpDir);
            FileWriter writer = new FileWriter(tmpFile);
            writer.write(txt);
            writer.close();
            
            String filePath = tmpFile.getAbsolutePath();
            System.out.println("File Path: " + filePath);
            Process javac = new ProcessBuilder()
                    .command("javac", filePath, "-target", "1.7", "-source", "1.7")
                    .directory(tmpDir)
                    .redirectOutput(ProcessBuilder.Redirect.INHERIT)
                    .redirectError(ProcessBuilder.Redirect.INHERIT)
                    .start();
            
            javac.waitFor();
            System.out.println("Exit value: " + javac.exitValue());
            
            // Find the generated '.class' file...
            File classFile = Files.list(tmpDir.toPath())
                    .filter(f -> f.toAbsolutePath()
                            .toString()
                            .endsWith(".class")
                    )
                    .map(Path::toFile)
                    .findAny()
                    .orElse(null);
            
            System.out.println("ClassFile: " + classFile.getName());
            
            filePath = classFile.getAbsolutePath();
            File outputFile = File.createTempFile("out", ".txt", tmpDir);
            System.out.println("File Path: " + filePath);
            Process javap = new ProcessBuilder()
                    .command("javap", "-c", filePath)
                    .directory(tmpDir)
                    .redirectOutput(outputFile)
                    .redirectError(ProcessBuilder.Redirect.INHERIT)
                    .start();
            
            javap.waitFor();
            System.out.println("Exit value: " + javap.exitValue());
            String output = Files.readAllLines(outputFile.toPath())
                    .stream()
                    .skip(1) // Drop first line...
                    .collect(Collectors.joining("\n"));
            OutputBytecode.setText(output);
            System.out.println("Output: " + output);
            
            String command = LLVM_JVM_PATH + "Main.exe " + getBaseName(classFile.getName()) + " -cp ./:" + LLVM_JVM_PATH + "rt";
            System.out.println(command);
            Process llvmJVM = new ProcessBuilder()
                    .command(LLVM_JVM_PATH + "Main.exe", "-cp", "./:" + LLVM_JVM_PATH + "rt", getBaseName(classFile.getName()))
                    .directory(tmpDir)
                    .start();
            llvmJVM.waitFor();
            
            String unoptimizedFile = tmpDir + "/unoptimizedIR.ll";
            String optimizedFile = tmpDir + "/optimizedIR.ll";
            new ProcessBuilder()
                    .command("llvm-as", "unoptimizedIR.ll", "-o", "unoptimized.bc")
                    .directory(tmpDir)
                    .start()
                    .waitFor();
            
            new ProcessBuilder()
                    .command("opt", "unoptimized.bc", "-dot-cfg", "-analyze")
                    .directory(tmpDir)
                    .start()
                    .waitFor();
            
            new ProcessBuilder()
                    .command("dot", "-Tpng", "cfg.main.dot", "-o", "unoptimizedIR.png")
                    .directory(tmpDir)
                    .start()
                    .waitFor();
            
            System.out.println("File: " + Paths.get(tmpDir + "/unoptimizedIR.png") + ", Exists: " + Files.exists(Paths.get(tmpDir + "/unoptimizedIR.png")));
            ImageIcon image = new ImageIcon(Paths.get(tmpDir + "/unoptimizedIR.png").toString());
            JLabel label = new JLabel("", image, JLabel.CENTER);
            OutputUnoptimizedIR.add( new JScrollPane(label), BorderLayout.CENTER );
            
            new ProcessBuilder()
                    .command("llvm-as", "optimizedIR.ll", "-o", "optimized.bc")
                    .directory(tmpDir)
                    .start()
                    .waitFor();
            
            new ProcessBuilder()
                    .command("opt", "optimized.bc", "-dot-cfg", "-analyze")
                    .directory(tmpDir)
                    .start()
                    .waitFor();
            
            new ProcessBuilder()
                    .command("dot", "-Tpng", "cfg.main.dot", "-o", "optimizedIR.png")
                    .directory(tmpDir)
                    .start()
                    .waitFor();
            
            System.out.println("File: " + Paths.get(tmpDir + "/optimizedIR.png") + ", Exists: " + Files.exists(Paths.get(tmpDir + "/optimizedIR.png")));
            image = new ImageIcon(Paths.get(tmpDir + "/optimizedIR.png").toString());
            label = new JLabel("", image, JLabel.CENTER);
            OutputOptimizedIR2.add( new JScrollPane(label), BorderLayout.CENTER );
            
//            output = Files.readAllLines(Paths.get(unoptimizedFile))
//                    .stream()
//                    .skip(3) // Drop header...
//                    .collect(Collectors.joining("\n"));
//            OutputUnoptimizedIR.setText(output);
//            
//            output = Files.readAllLines(Paths.get(optimizedFile))
//                    .stream()
//                    .skip(3) // Drop header...
//                    .collect(Collectors.joining("\n"));
//            OutputOptimizedIR.setText(output);
            
       } catch (Exception ex) {
            Logger.getLogger(Editor.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea OutputBytecode;
    private javax.swing.JPanel OutputOptimizedIR;
    private javax.swing.JPanel OutputOptimizedIR2;
    private javax.swing.JPanel OutputUnoptimizedIR;
    private javax.swing.JPanel TextEditorPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
